<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SecurityMonitorController;
use App\Http\Controllers\StoreController;
use Illuminate\Support\Facades\Route;

// Authentication Routes (Generated by Laravel UI)
Auth::routes();

// Public Routes
/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Authenticated Routes
Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');

    // Client Management
    Route::resource('clients', ClientController::class);
    Route::post('clients/{client}/regenerate-api-key', [ClientController::class, 'regenerateApiKey'])->name('clients.regenerateApiKey');

    // Store Management
    Route::get('stores', [StoreController::class, 'index'])->name('stores.index');
    Route::get("stores/create", [StoreController::class, "create"])->name("stores.create");
    Route::post("stores", [StoreController::class, "store"])->name("stores.store");
    Route::get('stores/{store}', [StoreController::class, 'show'])->name('stores.show');
    // Add routes for store sub-sections if needed (e.g., modules, server info)
    Route::get('stores/{store}/modules', [StoreController::class, 'showModules'])->name('stores.modules');
    Route::get('stores/{store}/server-info', [StoreController::class, 'showServerInfo'])->name('stores.serverInfo');
    Route::get('stores/{store}/stats', [StoreController::class, 'showStats'])->name('stores.stats');
    Route::get('stores/{store}/security', [StoreController::class, 'showSecurity'])->name('stores.security');

    // Security Monitoring
    Route::get('security', [SecurityMonitorController::class, 'dashboardOverview'])->name('security.overview');
    Route::post('security/check-updates', [SecurityMonitorController::class, 'runCheckUpdatesCommand'])->name('security.checkUpdates'); // Manual trigger
    Route::post('stores/{store}/security/{status}/apply', [SecurityMonitorController::class, 'markPatchAsApplied'])->name('security.markApplied');

    // User Profile (Optional)
    // Route::get("/profile", [ProfileController::class, "edit"])->name("profile.edit");
    // Route::patch("/profile", [ProfileController::class, "update"])->name("profile.update");
    // Route::delete("/profile", [ProfileController::class, "destroy"])->name("profile.destroy");
});
